In [1]:
import numpy as np
# 1번
a=np.arange(2,101,2).reshape(10, 5)
a

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [2]:
# 2번
a=a.reshape(2,5,5)
a

array([[[  2,   4,   6,   8,  10],
        [ 12,  14,  16,  18,  20],
        [ 22,  24,  26,  28,  30],
        [ 32,  34,  36,  38,  40],
        [ 42,  44,  46,  48,  50]],

       [[ 52,  54,  56,  58,  60],
        [ 62,  64,  66,  68,  70],
        [ 72,  74,  76,  78,  80],
        [ 82,  84,  86,  88,  90],
        [ 92,  94,  96,  98, 100]]])

In [3]:
# 3번
b = np.full((5,5),a[0][4][4])
b

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]])

In [4]:
# 4번
c = np.arange(b[0][0],1300,50).reshape(5,5).astype('U')
c

array([['50', '100', '150', '200', '250'],
       ['300', '350', '400', '450', '500'],
       ['550', '600', '650', '700', '750'],
       ['800', '850', '900', '950', '1000'],
       ['1050', '1100', '1150', '1200', '1250']], dtype='<U11')

In [5]:
# 5번
d = c.astype(np.float64)[4::-1,]
d

array([[1050., 1100., 1150., 1200., 1250.],
       [ 800.,  850.,  900.,  950., 1000.],
       [ 550.,  600.,  650.,  700.,  750.],
       [ 300.,  350.,  400.,  450.,  500.],
       [  50.,  100.,  150.,  200.,  250.]])

In [6]:
# 6번 
e = d[1:5,::-1]
e

array([[1000.,  950.,  900.,  850.,  800.],
       [ 750.,  700.,  650.,  600.,  550.],
       [ 500.,  450.,  400.,  350.,  300.],
       [ 250.,  200.,  150.,  100.,   50.]])

In [7]:
# 7번
f = e[0:,[0,1,3,4]]
f

array([[1000.,  950.,  850.,  800.],
       [ 750.,  700.,  600.,  550.],
       [ 500.,  450.,  350.,  300.],
       [ 250.,  200.,  100.,   50.]])

In [8]:
# 8번
g = np.append(f,f[0:,1:5:2].T, 0)
g

array([[1000.,  950.,  850.,  800.],
       [ 750.,  700.,  600.,  550.],
       [ 500.,  450.,  350.,  300.],
       [ 250.,  200.,  100.,   50.],
       [ 950.,  700.,  450.,  200.],
       [ 800.,  550.,  300.,   50.]])

In [9]:
# 9번
h = np.insert(g,2,g[0:,[0,3]].T,1)
h

array([[1000.,  950., 1000.,  800.,  850.,  800.],
       [ 750.,  700.,  750.,  550.,  600.,  550.],
       [ 500.,  450.,  500.,  300.,  350.,  300.],
       [ 250.,  200.,  250.,   50.,  100.,   50.],
       [ 950.,  700.,  950.,  200.,  450.,  200.],
       [ 800.,  550.,  800.,   50.,  300.,   50.]])

In [10]:
# 10번
h.sort(0)
h

array([[ 250.,  200.,  250.,   50.,  100.,   50.],
       [ 500.,  450.,  500.,   50.,  300.,   50.],
       [ 750.,  550.,  750.,  200.,  350.,  200.],
       [ 800.,  700.,  800.,  300.,  450.,  300.],
       [ 950.,  700.,  950.,  550.,  600.,  550.],
       [1000.,  950., 1000.,  800.,  850.,  800.]])

In [11]:
# 11번
import pandas as pd
i = pd.Series(h[5],index=[h[0].astype('i')]).astype('i')
i

250    1000
200     950
250    1000
50      800
100     850
50      800
dtype: int32

In [12]:
# 12번
i= pd.Series(np.where(i.values>800,np.nan,i.values),i.index)
i

250      NaN
200      NaN
250      NaN
50     800.0
100      NaN
50     800.0
dtype: float64

In [14]:
# 13번
j=pd.Series(np.where(i.values==800,800.,0.),i.index)
j

250      0.0
200      0.0
250      0.0
50     800.0
100      0.0
50     800.0
dtype: float64

In [28]:
# 14번
k = pd.Series(j.values.astype('str'),j.index)
k

250      0.0
200      0.0
250      0.0
50     800.0
100      0.0
50     800.0
dtype: object

In [29]:
k = pd.Series(k.values, index=range(1,13,2))
k

1       0.0
3       0.0
5       0.0
7     800.0
9       0.0
11    800.0
dtype: object